version: '3'

services: 
    postgres: 
        image: postgres:latest          # latest from docker hub

    redis: 
        image: redis:latest             # latest from docker hub

    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'

    api:
        build: 
            dockerfile: Dockerfile.dev  # name only
            context: ./server           # look in directory 
        volumes:
            - /app/node_modules         # keep node_modules inside container
            - ./server:/app             # for everything else look into ./server
        environment:                    # set env variables
            - REDIS_HOST=redis          # host name === service name 
            - REDIS_PORT=6379           
            - PGUSER=postgres
            - PGHOST=postgres           # host name === service name 
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432

    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app

    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app